default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root

development:
  <<: *default
  database: grape_db_development

test:
  <<: *default
  database: grape_db_test

production:
  <<: *default
  database: grape_db_production
